spring:
  cloud:
    stream:
      function:
        definition: queue1Sink;queue2Sink;failedSink
      bindings:
        queue1Sink-in-0:
          destination: demo-exchange
          group: demo-queue1
          consumer:
            max-attempts: 4
        queue2Sink-in-0:
          destination: demo-exchange
          group: demo-queue2
          consumer:
            max-attempts: 4
        failedSink-in-0:
          destination: failed-exchange
          group: failed-queue
        source-out-0:
          destination: demo-exchange
        failed-out-0:
          destination: failed-exchange
      rabbit:
        bindings:
          queue1Sink-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: routing-queue1
          queue2Sink-in-0:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: routing-queue2
          failedSink-in-0:
            consumer:
              queueNameGroupOnly: true
          #              requeueRejected: true
          source-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: headers['myRoutingKey']
          failed-out-0:
            producer:
              exchangeType: topic
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver